name: Linting

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Set up Jake
        uses: AstraBert/setup-jake@v0.1.0

      - name: Run formatter
        shell: bash
        run: jake format-check

      - name: Run linter
        shell: bash
        run: jake lint-check
